### ISSUE TITLE
Create tables in DB

### ISSUE THREAD

**Issue by olexandrger** [AlexandrGer/GradProjectNC#17]

**Comment by PavloRospopa** [comment]
не бачу сенсу розділяти даний таск на 4-х людей. я зараз залию фінальний варіант ерд(на мою думку)), відповім на питання (якщо будуть) про зміни, які я здійснив і приступлю до створення таблиць і всіх необхідних констреінтів. Краще розділити дао, сервіси і тд тп (які потрібні для реалізації продуктового каталогу) на інших людей

**Comment by olexandrger** [comment]
Вона на 3 кинута , дивись Assignees а не participants) Але думка слушна, це покищо приблизний варіант розподілу, далі дивитимемось по мірі винекнення завдань.
