### ISSUE TITLE
Implement order managing functionality

### ISSUE THREAD

**Issue by olexandrger** [AlexandrGer/GradProjectNC#64]
Implement order managing functionality.
System shall have:
 1. The ability to edit information about orders made by clients.
 2. The ability to change the status of order:
from “created” to “in progress” or “cancelled”;
from “in progress” to “completed” or “cancelled”
See  [Meeting minutes](https://docs.google.com/document/d/1JkOUUahTsNrfSyqGiIFbnXO-hH2NYEN3SKR3THgSBTA/edit?usp=sharing) for additional info.

**Comment by DeniGam** [comment]
Done
